<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsBody</name>
   <tag></tag>
   <elementGuidId>b8e72608-1f70-42b5-873e-53df6d3454fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name,'articleBody')]//div[contains(@class,'StoryBodyCompanionColumn')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Trump to Meet Congressional Leaders as Shutdown Stretches On' or . = 'Trump to Meet Congressional Leaders as Shutdown Stretches On')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>balancedHeadline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trump to Meet Congressional Leaders as Shutdown Stretches On</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-21b71713&quot;)/span[@class=&quot;balancedHeadline&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//*[contains(@name,'articleBody')]//div[contains(@class,'StoryBodyCompanionColumn')]</value>
   </webElementXpaths>
</WebElementEntity>
