<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsHeader</name>
   <tag></tag>
   <elementGuidId>f3e20d11-81a8-43bc-9571-abc79a29577b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class,'balancedHeadline')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'WASHINGTON — President Trump plans to host congressional leaders on Wednesday in the White House Situation Room for a border security briefing that could either be the latest skirmish over his wall or the beginnings of a resolution to a government shutdown that is stretching into its 12th day.The 3 p.m. gathering will be in the secure room in the White House basement where military operations are tracked and other sensitive discussions unfold, a conscious effort to infuse a sense of national-security crisis into the immigration discussion. It will be Mr. Trump’s first face-to-face meeting with Democratic leaders since a combative session last month when he said he would insist that any government spending bill include money for a wall on the southwestern border — and would proudly own the consequences if that meant a shutdown.Democrats have refused to allocate any money — let alone the $5 billion that Mr. Trump has demanded — for a large, physical barrier like the wall desired by the president to thwart illegal border crossings. Instead, Democrats, in full control of the House, will vote Thursday on two bills to fund most of the government through Sept. 30 and the Department of Homeland Security to Feb. 8.They would devote $1.3 billion for border security measures, such as enhanced surveillance and fortified fencing.' or . = 'WASHINGTON — President Trump plans to host congressional leaders on Wednesday in the White House Situation Room for a border security briefing that could either be the latest skirmish over his wall or the beginnings of a resolution to a government shutdown that is stretching into its 12th day.The 3 p.m. gathering will be in the secure room in the White House basement where military operations are tracked and other sensitive discussions unfold, a conscious effort to infuse a sense of national-security crisis into the immigration discussion. It will be Mr. Trump’s first face-to-face meeting with Democratic leaders since a combative session last month when he said he would insist that any government spending bill include money for a wall on the southwestern border — and would proudly own the consequences if that meant a shutdown.Democrats have refused to allocate any money — let alone the $5 billion that Mr. Trump has demanded — for a large, physical barrier like the wall desired by the president to thwart illegal border crossings. Instead, Democrats, in full control of the House, will vote Thursday on two bills to fund most of the government through Sept. 30 and the Department of Homeland Security to Feb. 8.They would devote $1.3 billion for border security measures, such as enhanced surveillance and fortified fencing.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-u5vfum StoryBodyCompanionColumn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WASHINGTON — President Trump plans to host congressional leaders on Wednesday in the White House Situation Room for a border security briefing that could either be the latest skirmish over his wall or the beginnings of a resolution to a government shutdown that is stretching into its 12th day.The 3 p.m. gathering will be in the secure room in the White House basement where military operations are tracked and other sensitive discussions unfold, a conscious effort to infuse a sense of national-security crisis into the immigration discussion. It will be Mr. Trump’s first face-to-face meeting with Democratic leaders since a combative session last month when he said he would insist that any government spending bill include money for a wall on the southwestern border — and would proudly own the consequences if that meant a shutdown.Democrats have refused to allocate any money — let alone the $5 billion that Mr. Trump has demanded — for a large, physical barrier like the wall desired by the president to thwart illegal border crossings. Instead, Democrats, in full control of the House, will vote Thursday on two bills to fund most of the government through Sept. 30 and the Department of Homeland Security to Feb. 8.They would devote $1.3 billion for border security measures, such as enhanced surveillance and fortified fencing.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@class,'balancedHeadline')]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//*[contains(@class,'balancedHeadline')]</value>
   </webElementXpaths>
</WebElementEntity>
